<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9647e4ab-be66-4205-a2a9-293031bb5318</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.3" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Sylvan.Data.Csv" Version="1.4.4" />
    <PackageReference Include="Syncfusion.Blazor.Buttons" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Cards" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.DataForm" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Inputs" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.LinearGauge" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.MultiColumnComboBox" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Popups" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.RichTextEditor" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.SfPdfViewer" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.SplitButtons" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="34.1.33" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Data\" />
  </ItemGroup>
</Project>
