// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReachingOutDB.Data;

#nullable disable

namespace ReachingOutDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717143751_CreatedMiscSettings")]
    partial class CreatedMiscSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReachingOutDB.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("CustomBP")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DmQty")
                        .HasColumnType("int");

                    b.Property<int?>("DmQtyQ1")
                        .HasColumnType("int");

                    b.Property<int?>("DmQtyQ2")
                        .HasColumnType("int");

                    b.Property<int?>("DmQtyQ3")
                        .HasColumnType("int");

                    b.Property<int?>("DmQtyQ4")
                        .HasColumnType("int");

                    b.Property<int?>("IntlQty")
                        .HasColumnType("int");

                    b.Property<int?>("IntlQtyQ1")
                        .HasColumnType("int");

                    b.Property<int?>("IntlQtyQ2")
                        .HasColumnType("int");

                    b.Property<int?>("IntlQtyQ3")
                        .HasColumnType("int");

                    b.Property<int?>("IntlQtyQ4")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LtlQty")
                        .HasColumnType("int");

                    b.Property<int?>("LtlQtyQ1")
                        .HasColumnType("int");

                    b.Property<int?>("LtlQtyQ2")
                        .HasColumnType("int");

                    b.Property<int?>("LtlQtyQ3")
                        .HasColumnType("int");

                    b.Property<int?>("LtlQtyQ4")
                        .HasColumnType("int");

                    b.Property<string>("NotesQ1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesQ2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesQ3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesQ4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PostalQty")
                        .HasColumnType("int");

                    b.Property<int?>("PostalQtyQ1")
                        .HasColumnType("int");

                    b.Property<int?>("PostalQtyQ2")
                        .HasColumnType("int");

                    b.Property<int?>("PostalQtyQ3")
                        .HasColumnType("int");

                    b.Property<int?>("PostalQtyQ4")
                        .HasColumnType("int");

                    b.Property<int>("QtyQ1")
                        .HasColumnType("int");

                    b.Property<int>("QtyQ2")
                        .HasColumnType("int");

                    b.Property<int>("QtyQ3")
                        .HasColumnType("int");

                    b.Property<int>("QtyQ4")
                        .HasColumnType("int");

                    b.Property<bool>("SpecialNoteUPS")
                        .HasColumnType("bit");

                    b.Property<int?>("UpsQty")
                        .HasColumnType("int");

                    b.Property<int?>("UpsQtyQ1")
                        .HasColumnType("int");

                    b.Property<int?>("UpsQtyQ2")
                        .HasColumnType("int");

                    b.Property<int?>("UpsQtyQ3")
                        .HasColumnType("int");

                    b.Property<int?>("UpsQtyQ4")
                        .HasColumnType("int");

                    b.Property<bool>("VariableQty")
                        .HasColumnType("bit");

                    b.Property<int?>("YearlyBillingQuarter")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 2000,
                            Active = true,
                            CustomBP = false,
                            CustomerName = "Mennonite Church",
                            Location = "PA",
                            QtyQ1 = 0,
                            QtyQ2 = 0,
                            QtyQ3 = 0,
                            QtyQ4 = 0,
                            SpecialNoteUPS = false,
                            VariableQty = false
                        });
                });

            modelBuilder.Entity("ReachingOutDB.Data.MiscSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MagazineWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MiscSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MagazineWeight = 0.06m
                        });
                });

            modelBuilder.Entity("ReachingOutDB.Data.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<bool>("BpUpdate")
                        .HasColumnType("bit");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DmQty")
                        .HasColumnType("int");

                    b.Property<string>("HoldNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("IntlCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IntlQty")
                        .HasColumnType("int");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("LTLCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LtlQty")
                        .HasColumnType("int");

                    b.Property<string>("NotesForInvoicing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PostalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PostalQty")
                        .HasColumnType("int");

                    b.Property<int?>("PpOrderNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("PubShipping")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PubUsps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<string>("SpecialNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UpsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpsQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<bool?>("YearlyBilling")
                        .HasColumnType("bit");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("9b19ad13-0c8c-43dc-8c7d-9d4f3e1e485d"),
                            Archived = false,
                            BpUpdate = false,
                            CustomerId = 2000,
                            JobStatus = 1,
                            Qty = 0,
                            Quarter = 3,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("ReachingOutDB.Data.OrderAuditLog", b =>
                {
                    b.Property<Guid>("OrderAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderAuditLogId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderAuditLogs");

                    b.HasData(
                        new
                        {
                            OrderAuditLogId = new Guid("02bbd91b-1be0-4640-b82f-66b38ba448b9"),
                            Action = "Updated",
                            NewValue = "New Value",
                            OldValue = "Old Value",
                            OrderId = new Guid("9b19ad13-0c8c-43dc-8c7d-9d4f3e1e485d"),
                            PropertyName = "Some Property",
                            Timestamp = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Anonymous"
                        });
                });

            modelBuilder.Entity("ReachingOutDB.Data.Package", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("MailClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PackageOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PackageOptionId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("07dd94e4-a0c8-43c8-babc-200a8864d02c"),
                            Address = "123 Main",
                            City = "Ripley",
                            ContactName = "Contact name",
                            CustomerId = 2000,
                            MailClass = "FCF",
                            PackageOptionId = new Guid("9b19ad13-0c8c-43dc-8c7d-9d4f3e1e485c"),
                            Qty = 1,
                            State = "NY",
                            ZipCode = "14775"
                        });
                });

            modelBuilder.Entity("ReachingOutDB.Data.PackageOption", b =>
                {
                    b.Property<Guid>("PackageOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PackageDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PackagingWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PackageOptionId");

                    b.ToTable("PackageOptions");

                    b.HasData(
                        new
                        {
                            PackageOptionId = new Guid("9b19ad13-0c8c-43dc-8c7d-9d4f3e1e485c"),
                            PackageDescription = "10x13 plastic sleeve",
                            PackagingWeight = 0.1m
                        });
                });

            modelBuilder.Entity("ReachingOutDB.Data.ShippingSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BoxDiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BoxDiscountThreshold")
                        .HasColumnType("int");

                    b.Property<decimal>("HandlingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MarkupPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PerBoxFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityPerBox")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ShippingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoxDiscountPercentage = 0.15m,
                            BoxDiscountThreshold = 4,
                            HandlingFee = 4m,
                            MarkupPercentage = 0.6m,
                            Name = "UPS",
                            PerBoxFee = 1.75m,
                            QuantityPerBox = 750,
                            UpdatedAt = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BoxDiscountPercentage = 0.15m,
                            BoxDiscountThreshold = 4,
                            HandlingFee = 2m,
                            MarkupPercentage = 0.3m,
                            Name = "INTL",
                            PerBoxFee = 1.25m,
                            QuantityPerBox = 750,
                            UpdatedAt = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BoxDiscountPercentage = 0.15m,
                            BoxDiscountThreshold = 4,
                            HandlingFee = 25m,
                            MarkupPercentage = 0.15m,
                            Name = "LTL",
                            PerBoxFee = 1.25m,
                            QuantityPerBox = 750,
                            UpdatedAt = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BoxDiscountPercentage = 0.15m,
                            BoxDiscountThreshold = 4,
                            HandlingFee = 0m,
                            MarkupPercentage = 0.1m,
                            Name = "USPS",
                            PerBoxFee = 1.5m,
                            QuantityPerBox = 200,
                            UpdatedAt = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ReachingOutDB.Data.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProfileId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserProfileId = 1,
                            Active = true,
                            Name = "Ryan Stauffer",
                            Role = 1
                        });
                });

            modelBuilder.Entity("ReachingOutDB.Data.Order", b =>
                {
                    b.HasOne("ReachingOutDB.Data.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ReachingOutDB.Data.OrderAuditLog", b =>
                {
                    b.HasOne("ReachingOutDB.Data.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ReachingOutDB.Data.Package", b =>
                {
                    b.HasOne("ReachingOutDB.Data.Customer", "Customer")
                        .WithMany("Packages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReachingOutDB.Data.PackageOption", "PackageOption")
                        .WithMany()
                        .HasForeignKey("PackageOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PackageOption");
                });

            modelBuilder.Entity("ReachingOutDB.Data.Customer", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
